name: POGO Events Digest

on:
  schedule:
    - cron: "0 9 1 * *"   # 09:00 UTC on the 1st of each month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      END: ${{ steps.dates.outputs.END }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compute date range (full history → today)
        id: dates
        run: |
          echo "START=2024-06-01" >> $GITHUB_OUTPUT
          echo "END=$(date -u +%F)" >> $GITHUB_OUTPUT

      - name: Restore pogo_library cache
        id: cache-lib
        uses: actions/cache/restore@v4
        with:
          path: pogo_library
          key: pogolib-${{ steps.dates.outputs.END }}
          restore-keys: |
            pogolib-

      - name: Build library (FULL RANGE, no max)
        run: |
          python build_pogo_library.py \
            --start "${{ steps.dates.outputs.START }}" \
            --end   "${{ steps.dates.outputs.END }}" \
            --out pogo_library

      - name: Save pogo_library cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: pogo_library
          key: pogolib-${{ steps.dates.outputs.END }}

      - name: Build digest + ICS
        run: |
          python digest_from_library.py \
            --lib pogo_library \
            --out POGO_Digest.xlsx \
            --ics POGO_Events.ics

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: POGO_Digest_${{ steps.dates.outputs.END }}
          path: |
            POGO_Digest.xlsx
            POGO_Events.ics
            pogo_library/niantic/index.json
            pogo_library/leekduck/index.json

      - name: Commit stable copies to repo (always available in app)
        run: |
          mkdir -p outputs/latest
          cp POGO_Digest.xlsx outputs/latest/POGO_Digest.xlsx
          cp POGO_Events.ics outputs/latest/POGO_Events.ics
          {
            echo "# Latest POGO Digest"
            echo "- Built on: ${{ steps.dates.outputs.END }}"
            echo "- Range: ${{ steps.dates.outputs.START }} → ${{ steps.dates.outputs.END }}"
            echo "- Files: POGO_Digest.xlsx, POGO_Events.ics"
          } > outputs/latest/README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add outputs/latest/ pogo_library/niantic/index.json pogo_library/leekduck/index.json
          git commit -m "Update latest digest: ${{ steps.dates.outputs.START }} → ${{ steps.dates.outputs.END }}" || echo "No changes to commit"
          git push

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: POGO_Digest_${{ needs.build.outputs.END }}
          path: dist

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pogo-digest-${{ needs.build.outputs.END }}
          name: "POGO Digest ${{ needs.build.outputs.END }}"
          body: "Automated monthly digest (June 2024 → ${{ needs.build.outputs.END }})."
          files: |
            dist/POGO_Digest.xlsx
            dist/POGO_Events.ics